### ISSUE TITLE
Please convert to Swift 4/5

### ISSUE THREAD

**Issue by mrtokii** [TinkoffCreditSystems/tcstableviewrowactionfactory#2]
'NSAttributedStringKey' has been renamed to 'NSAttributedString.Key' - the pod won't build

**Comment by SviRiDoFFtru** [comment]
> 'NSAttributedStringKey' has been renamed to 'NSAttributedString.Key' - the pod won't build

I updated my repository to version 1.1.0(updated to swift 4.2) and this issue is resolved
